config/routes.rb
Rails.application.routes.draw do
  
  
  
  root 'articles#index'
  get "about", to: 'pages#about'
  
  resources :articles do
    resources :comments
  end
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

  get 'search', to: 'articles#search'

  namespace 'api' do
    namespace 'v1' do
      resources :users
    end
  end

  get 'test', to: 'users#test'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :article_categories
  has_many :categories, through: :article_categories
  mount_uploader :image, ImageUploader
  after_commit :remove_previously_stored_image, on: :update
  validates :title, presence: true, length: {minimum: 3, maximum:20}
  validates :description, presence: true, length: {minimum: 10, maximum: 10000}
  validates :user_id, presence: true

  def self.search(p)
  	p.strip!
  	p.downcase!
  	res1 = ( User.where("username like ?", "%#{p}%") + Article.where("title like ?", "%#{p}%") )
  	return nil unless res1
  	res1
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show, :search]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @articles = Article.paginate(page: params[:page], per_page:5)
  end
  
  def new
    @article = Article.new
    @image = ImageUploader.new
  end
  
  def create
    # debugger #for debuggin porpuse in the server terminal. to see what has been passed on
    @article = Article.new(article_params)
    @image = params[:image]
    @article.user = current_user if logged_in?# ///
    if @article.save
      flash[:success] = "Article was created succesfully"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @article.update(article_params)
      flash[:success] = "Article was updated succesfully"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def show
  end
  
  def destroy
    @article.destroy
    flash[:danger] = "Article was deleted..."
    redirect_to articles_path
  end

  def search
    if params[:s].blank?
      flash.now[:danger] = "You have entered an empty string !"
    else
      @objs = Article.search(params[:s])
      flash.now[:danger] = "No results match your search criteria, please try again" if @objs.blank?
    end
    # render json: @objs
    render partial: 'shared/results'
  end
  
  private
  
  def set_article
    @article = Article.find(params[:id])
  end
  
  def article_params
    params.require(:article).permit(:title, :description, :image, category_ids: [])
  end
  
  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You can only edit your own articles !"
      redirect_to articles_path
    end
  end
  
end

app/views/articles/_articles.html.erb
<% obj.each do |article| %>
  <div class="row">

      <div class="">

        <div class="well well-lg">

          <div class="article-title" align="center">

            <%= link_to article.title, article_path(article) %>

          </div>

          <div class="article-body index">

            <%= truncate(article.description, length: 500) %>
          </div>
          <div>
              <%= (image_tag article.image, class: "col-xs-12") if article.image? %>
          </div>

            <div class= "article-meta-details">
              <small>Created by: <%= link_to "#{article.user.username}",  user_path(article.user) %> ,
              <%= time_ago_in_words(article.created_at) %> ago,
               last updated: <%= time_ago_in_words(article.updated_at) %> ago
              </small>
            </div>

            <% if article.categories.any? %>
              <p>Categories: <%= render article.categories %></p>
            <% end %>

            <div>
              <hr />
              <b>Comments: </b> <br/>
              <%= render article.comments %>
              <%= render 'comments/new', art: article %>
              <hr />
            </div>

          <div class="article-actions">
          <% if logged_in? && (current_user == article.user || current_user.admin?) %>
            <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete this article", article_path(article), method: :delete,
                      data: { confirm: "Are you sure you want to delete the article?"},
                      class: "btn btn-xs btn-danger" %>
          <% end %>
          </div>

        </div>

      </div>

  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class= "row">
  <div class="col-xs-12">
    
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class= "form-group">
          <%= f.label :title, class: "control-label col-sm-2" %> 
      <div class= "col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of Article", autofocus: true %>
      </div>
    </div>
    
    <div class="form-group">
          <%= f.label :description, class: "control-label col-sm-2" %>
      <div class= "col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of Article", autofocus: true %>
      </div>
    </div>

    <div class= "form-group">
          <%= f.label :image, class: "control-label col-sm-2" %> 
      <div class= "col-sm-8">
          <%= f.file_field :image, class: "form-control" %>
      </div>
    </div>


    <div class="form-group">
      <div class="row">
        <div class="col-sm-offset-2 col-sm-8">
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
          <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
          <% end %>
        </div>
      </div>
    </div>
    
    <div class= "form-group">
      <div class= "col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-danger btn-lg"%>        
      </div>
    </div>
    
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
    </div>


  </div>
</div>

<% end %>

app/views/articles/edit.html.erb
<h1 align="center"> Edit an existing Article </h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="well">
  <h1 align="center">Listing all articles</h1>
  <%= render 'articles', obj: @articles %>
  <%= will_paginate %>
</div>

app/views/articles/index1.html.erb
<div class= "table-responsive">
  <table border="0" class= "table">
      <tr>
      <th> Titles </th>
      <th>Descriptions</th>
      <th colspan="3" align="center">Table Actions</th>
    </tr>
    <% @articles.each do |ar| %>
    <tr>
      <td > <%= ar.title %> </td>
      <td> <%= truncate(ar.description, length: 50) %>  </td>
      <td> <%= link_to 'Edit', edit_article_path(ar), class:"btn btn-xs btn-primary btn-indix"%> </td>
      <td> <%= link_to 'Show', article_path(ar), class:"btn btn-xs btn-success btn-indix" %> </td>
      <td> <%= link_to 'Delete', article_path(ar), method: :delete, data: {confirm: "Are you sure ?"} , class:"btn btn-xs btn-danger btn-indix"%> </td>
    </tr>
  
    <% end %>
  </table>
</div>



  <li class= "username"> <%= link_to "#{User.find(params[session[:user_id]])}", user_path(User.find(params[session[:user_id]]) %> </li>

app/views/articles/new.html.erb
<h1 align = "center"> Create new Article </h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h3 align = "center"> Title : <%= @article.title %> </h3>

<div class =  "col-xs-8 col-xs-offset-2 well well-lg">
  <% if @article.user %>
  <div class= "row">
      <ul class= "listing">
          <div class="col-xs-2 col-md-1">
              <li> 
                  <% if @article.user.avatar? %>
                     <%= image_tag @article.user.avatar, height: 60, width: 60, class: "img-circle" %>
                  <% else %>
                    <%= gravatar_for @article.user, size: 60 , class: "img-circle" %>
                  <% end %> 
              </li>
            </div>
            <div class="col-xs-2 art_show_username">
              <li class= "article-title"> <%= link_to @article.user.username, user_path(@article.user) %> 
              </li>
            </div>
      </ul>
  <% end %>
  </div>
  
  <div class="row">
    <div class="col-xs-12 index">
        <%= truncate(@article.description, length: 1000) %>
    </div>
        <%= (image_tag @article.image, class: "col-xs-10 col-xs-offset-1") if @article.image? %>
  </div>

  <div>
   <hr />
    <b>Comments: </b> <br/>
    <div id="comments">
      <%= render  @article.comments %>
    </div>
    <div id="newcom">
      <%= render 'comments/new', art: @article %>
    </div>
  </div>
  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %></p>
  <% end %>
  
  <div class="article-action">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to 'Edit this article', edit_article_path(@article), class: "btn btn-xs btn-primary "%>
      <%= link_to 'Delete this article', article_path(@article), method: :delete, data:{confirm: "Are you sure ?"}, class: "btn btn-xs btn-danger "%>
    <% end %>
    <%= link_to 'View all articles', articles_path, class: "btn btn-xs btn-success"%>
  </div>
</div>