config/routes.rb
Rails.application.routes.draw do
  
  
  
  root 'articles#index'
  get "about", to: 'pages#about'
  
  resources :articles do
    resources :comments
  end
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

  get 'search', to: 'articles#search'

  namespace 'api' do
    namespace 'v1' do
      resources :users
    end
  end

  get 'test', to: 'users#test'

end

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class= "col-xs-8 col-xs-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          <%= pluralize(obj.errors.count, "error") %>
            stopped form being submitted :
        </h2>
        <div class= "panel-body">
          <ul>
            <% obj.errors.full_messages.each do |e| %>
              <li> <%= e %> </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_results.html.erb
<% if params[:action] == 'search' %>
 	<%= render 'layouts/msgs' %>
<% end %>

<div class="container">
	<% if @objs %>
		<% if @objs.size > 0 %>
			<div class="results-block well col-md-8 col-md-offset-2">
				
					<p align="center"> <strong> Results</strong></p>
					<hr>
					<table class="col-md-12" >
						<% @objs.each do |r| %>
							<% if r.instance_of? (Article) %>
								<tr>
									<td> <strong> Title :</strong> <i class="glyphicon glyphicon-file"></i> <%= r.title  %></td>
									<td> <strong> Description :</strong> <%= truncate(r.description, length: 30) %></td>
									<td><%= link_to "View", article_path(r), class: "btn btn-xs btn-success" %></td>
								</tr>
							<% else %>
								<tr class="users-search-results">
									<td> <strong> Username :</strong> <i class="glyphicon glyphicon-user"></i> <%= r.username  %></td>
									<td> <strong> Email :</strong> <%= truncate(r.email, length: 30) %></td>
									<td><%= link_to "Profile", user_path(r), class: "btn btn-xs btn-warning" %></td>
								</tr>
							<% end %>
						<% end %>
					</table>
			</div>
		<% end %>
	<% end %>
</div>