config/routes.rb
Rails.application.routes.draw do
  
  
  
  root 'articles#index'
  get "about", to: 'pages#about'
  
  resources :articles do
    resources :comments
  end
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

  get 'search', to: 'articles#search'

  namespace 'api' do
    namespace 'v1' do
      resources :users
    end
  end

  get 'test', to: 'users#test'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :article_categories
	has_many :articles, through: :article_categories
	validates :name, presence: true, length: {minimum: 3, maximum: 25}
	validates_uniqueness_of :name
	
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :require_admin, except: [:index, :show]
	
	def index
		@categories = Category.paginate(page: params[:page], per_page: 5)
	end

	def new
		@category = Category.new		
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:success] = "Category was created successfully"
			redirect_to categories_path
		else
			render 'new'
		end
	end

	def show
		@category = Category.find(params[:id])
		@cat_arts = @category.articles.paginate(page: params[:page], per_page: 5)		
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])

		if @category.update(category_params)
			flash[:success] = "Category name was updated successfully"
			redirect_to @category
		else
			render 'edit'
		end
	end


	private

	def category_params
		params.require(:category).permit(:name)
	end

	def require_admin
		if !logged_in? or (logged_in? and !current_user.admin?)
			flash[:danger] = "Only admins can perfum that action"
			redirect_to categories_path
		end
		
	end
	
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %>  </span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<div class="form-group">
	<div class="control-label col-sm-2">
		<%= f.label :name %>
	</div>
	<div class="col-sm-8">
		<%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
	</div>
</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<%= f.submit class: 'btn btn-primary btn-lg' %>
	</div>
</div>
<% end %>

app/views/categories/edit.html.erb
<h1 align="center">Edit Category Name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center"> Listing All Categories</h1>

<div align="center">
	<% @categories.each do |category| %>
	<ul class="listing">
		<div class="row">
			<div class="well col-md-4 col-md-offset-4">
				<li class="article-title">
					<%= link_to "#{category.name}", category_path(category) %>
				</li>
				<li> <small><%= pluralize(category.articles.count, "article") %> </small></li>
			</div>
		</div>
	</ul>
	<% end %>
	<%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1>
<div align="center">
	<% if logged_in? and current_user.admin? %>
	<div class="row">
		<span class="badge"><%= link_to "Edit Category Name", edit_category_path(@category) %></span>
	</div>
	<% end %>

</div>
<%= render 'articles/articles', obj: @cat_arts %>
<div align="center">
	<%= will_paginate @cat_arts %>
</div>