config/routes.rb
Rails.application.routes.draw do
  
  
  
  root 'articles#index'
  get "about", to: 'pages#about'
  
  resources :articles do
    resources :comments
  end
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

  get 'search', to: 'articles#search'

  namespace 'api' do
    namespace 'v1' do
      resources :users
    end
  end

  get 'test', to: 'users#test'

end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class= "footer">
      <samll>
        Copyright &copy; <a id = "red" href="http://qasemi.dx.am">Hafizullah Qasemi</a>
      </samll>
    <nav>
      <ul>
        <li> <a href="http://qasemi.dx.am/#about"> About</a></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_msgs.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name,msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <%  end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Alpa blog', articles_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          <li> <%= link_to 'Users', users_path , id: "red"%> </li>
        <% if logged_in? %>
          <li><%= link_to 'Create New Article', new_article_path , id: "red" %></li>
        <% else %>
          <li><%= link_to 'Home', root_path, id: "red" %></li>
        <% end %>
        
      </ul>

      <div class="navbar-form navbar-left">
        <div class="form-group">
          <%= form_tag search_path, remote: true, method: :get, id: "lookup-form" do %>
              <%= text_field_tag :s, params[:s], placeholder: "search something", class: "form-control" %>
              <%= button_tag(type: :submit, class: "btn btn-default") do %>
                <i class="glyphicon glyphicon-search"></i> Search
              <% end %>
          <% end %>
        </div>
      </div>

      <% if logged_in? %>
        <ul class= "nav navbar-nav navbar-right">
            <li> <%= (image_tag current_user.avatar, width: 50, height: 50, class: "img-circle") if current_user.avatar? %></li>
          <% if current_user.admin? %>
            <li> <%= link_to "#{current_user.username}", user_path(current_user), id: "red", class: "username admin" %></li>
          <% else %>
            <li> <%= link_to "#{current_user.username}", user_path(current_user), id: "red", class: "username" %></li>
          <% end %>
          <li> <%= link_to 'Edit your profile', edit_user_path(current_user), id: "red" %> </li>
          <li> <%= link_to 'Log out', logout_path, method: :delete , id: "red" %></li>
        </ul>
      <% else %>
         <ul class= "nav navbar-nav navbar-right">
          <li> <%= link_to 'Log in', login_path , id: "red"%></li>
          <li> <%= link_to 'Sign up', signup_path , id: "red"%></li>
        </ul>
      <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlpaBlog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- ,obj: @user -->
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/msgs' %>
  <div id="results">
    <%= render 'shared/results' %>
  </div>

  <div class= "container-fluid">
    <div class="row">
        <div class="col-md-7 col-md-offset-1" align="center">
        <%= yield %>
      </div>
      <div class="col-md-4">
        <div >
          <%= link_to "All Categories", categories_path, class: "list-group-item list-group-item-action active" %>
            <% Category.all.each do |category| %>
            <%= link_to "#{category.name}", category_path(category), class: "list-group-item list-group-item-action" %>
            <% end %>
            <% if logged_in? and current_user.admin? %>
              <span role="separator" class="divider"></span>
              <%= link_to "Create New Category", new_category_path, class: "list-group-item list-group-item-action active" %>
            <% end %>
        </div>
      </div>
    </div>
    

    <div class="footer-div">
      <%= render 'layouts/footer' %>
    </div>
  </div>
<%= debug(params) if Rails.env.development? %>

</body>
</html>